trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: CmdLine@1
    inputs:
      filename: Sn.exe
      arguments: -Vr *,31bf3856ad364e35
  - task: MSBuild@1
    inputs:
      solution: build.proj