trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: CmdLine@1
    inputs:
      filename: dir.exe
      arguments: "C:\\Program Files\\Microsoft SDKs\\Windows"
  - task: MSBuild@1
    inputs:
      solution: build.proj