trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: CmdLine@1
    inputs:
      filename: dir
      arguments: C:\Program Files
  - task: MSBuild@1
    inputs:
      solution: build.proj